"""增加用户图像的图床地址字段

Revision ID: 105432cb8a8b
Revises: 4fd18cc4c0a5
Create Date: 2025-01-13 22:42:06.565388

"""

# revision identifiers, used by Alembic.
revision = '105432cb8a8b'
down_revision = '4fd18cc4c0a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
