"""1.修改用户模型 2.增加Tag标签模型

Revision ID: 3cbdaca38297
Revises: a48059966c2d
Create Date: 2025-08-02 20:07:14.766151

"""

# revision identifiers, used by Alembic.
revision = '3cbdaca38297'
down_revision = 'a48059966c2d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from sqlalchemy.sql import table, column
from sqlalchemy import JSON

default_social = {
    'github': None,
    'qq': None,
    'wechat': None,
    'bilibili': None,
    'twitter': None,
    'tiktok': None,
    'rednote': None,
    'email': None
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_tag',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('bg_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_account', sa.JSON(), nullable=True))
    # 补齐旧数据，让已注册的用户的social_account更新为默认值
    users = table('users', column('social_account', JSON))
    op.execute(
        users.update().where(users.c.social_account == None).values(social_account=default_social)
    )
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'social_account')
    op.drop_column('users', 'bg_image')
    op.drop_column('users', 'sex')
    op.drop_table('user_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
