"""评论模型_支持存储回复

Revision ID: 4fd18cc4c0a5
Revises: b9584696b505
Create Date: 2024-12-22 23:22:02.145540

"""

# revision identifiers, used by Alembic.
revision = '4fd18cc4c0a5'
down_revision = 'b9584696b505'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
