"""文章模型为[内容和摘要]，[是否删除和时间戳]增加联合索引

Revision ID: 5944dfb32ebe
Revises: da589f891f75
Create Date: 2026-03-24 18:48:52.980126

"""

# revision identifiers, used by Alembic.
revision = '5944dfb32ebe'
down_revision = 'da589f891f75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ft_posts_summary_content', 'posts', ['summary', 'content'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.create_index('idx_posts_deleted_timestamp', 'posts', ['deleted', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_deleted_timestamp', table_name='posts')
    op.drop_index('ft_posts_summary_content', table_name='posts', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    # ### end Alembic commands ###
