"""日志表增加新字段

Revision ID: 5cf3d7363540
Revises: 105432cb8a8b
Create Date: 2025-03-24 20:40:31.087974

"""

# revision identifiers, used by Alembic.
revision = '5cf3d7363540'
down_revision = '105432cb8a8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('browser', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('browser_version', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('os', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('os_version', sa.String(length=50), nullable=True))
    op.add_column('log', sa.Column('device', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'device')
    op.drop_column('log', 'os_version')
    op.drop_column('log', 'os')
    op.drop_column('log', 'browser_version')
    op.drop_column('log', 'browser')
    op.drop_column('log', 'city')
    op.drop_column('log', 'country')
    # ### end Alembic commands ###
