"""文章表增加has_more字段

Revision ID: 6485652d598c
Revises: 5944dfb32ebe
Create Date: 2026-03-30 19:01:15.909855

"""

# revision identifiers, used by Alembic.
revision = '6485652d598c'
down_revision = '5944dfb32ebe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('has_more', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'has_more')
    # ### end Alembic commands ###
