"""增加文章图片url字段

Revision ID: 77e1dc7ba120
Revises: 26f63d68afbb
Create Date: 2025-04-27 22:00:41.158545

"""

# revision identifiers, used by Alembic.
revision = '77e1dc7ba120'
down_revision = '26f63d68afbb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=mysql.ENUM('COMMENT', 'REPLY', 'LIKE', 'CHAT', 'AT'),
               type_=sa.Enum('AT', 'COMMENT', 'REPLY', 'LIKE', 'CHAT', name='notificationtype'),
               existing_nullable=True)
    op.add_column('posts', sa.Column('type', sa.Enum('TEXT', 'IMAGE', name='posttype'), nullable=True))
    op.add_column('posts', sa.Column('images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'images')
    op.drop_column('posts', 'type')
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('AT', 'COMMENT', 'REPLY', 'LIKE', 'CHAT', name='notificationtype'),
               type_=mysql.ENUM('COMMENT', 'REPLY', 'LIKE', 'CHAT', 'AT'),
               existing_nullable=True)
    # ### end Alembic commands ###
