"""Post模型增加content字段

Revision ID: 9a2c956701e0
Revises: f67229d9f8fa
Create Date: 2025-12-27 23:09:31.662732

"""

# revision identifiers, used by Alembic.
revision = '9a2c956701e0'
down_revision = 'f67229d9f8fa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import Boolean

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('has_image', sa.Boolean(), nullable=True))
    posts = table('posts', column('has_image', Boolean))
    op.execute(
        posts.update().where(posts.c.has_image.is_(None)).values(has_image=False)
    )

    # 直接执行 ALTER TABLE 时，MySQL 会尝试将 'IMAGE' 强制转换为新类型，但失败并报错 "Data truncated"。
    # 更新现有 'IMAGE' 类型为 'TEXT'。
    op.execute("UPDATE posts SET type = 'TEXT' WHERE type = 'IMAGE'")
    op.alter_column('posts', 'type',
               existing_type=mysql.ENUM('TEXT', 'IMAGE'),
               type_=sa.Enum('TEXT', 'MARKDOWN', name='posttype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 更新现有 'MARKDOWN' 类型为 'TEXT' 以适应旧的 ENUM
    op.execute("UPDATE posts SET type = 'TEXT' WHERE type = 'MARKDOWN'")
    op.alter_column('posts', 'type',
               existing_type=sa.Enum('TEXT', 'MARKDOWN', name='posttype'),
               type_=mysql.ENUM('TEXT', 'IMAGE'),
               existing_nullable=True)
    op.drop_column('posts', 'has_image')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
