"""用户表增加has_password字段

Revision ID: 9ccbee803e77
Revises: b3c934c4a64f
Create Date: 2026-01-23 14:49:48.875153

"""

# revision identifiers, used by Alembic.
revision = '9ccbee803e77'
down_revision = 'b3c934c4a64f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Boolean


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_password', sa.Boolean(), nullable=True))
    users = table('users', column('has_password', Boolean))
    op.execute(
        users.update().where(users.c.has_password.is_(None)).values(has_password=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_password')
    # ### end Alembic commands ###
