"""文章模型增加逻辑删除字段

Revision ID: a315517f06bc
Revises: ed10582b0d7b
Create Date: 2025-11-20 14:06:58.513687

"""

# revision identifiers, used by Alembic.
revision = 'a315517f06bc'
down_revision = 'ed10582b0d7b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Boolean

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=True))
    # 补齐旧数据，让已注册的用户的deleted更新为默认值
    posts = table('posts', column('deleted', Boolean))
    op.execute(
        posts.update().where(posts.c.deleted.is_(None)).values(deleted=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted')
    # ### end Alembic commands ###
