"""新增图片模型

Revision ID: a48059966c2d
Revises: 77e1dc7ba120
Create Date: 2025-05-14 20:52:34.749063

"""

# revision identifiers, used by Alembic.
revision = 'a48059966c2d'
down_revision = '77e1dc7ba120'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('describe', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('MOVIE', 'BOOK', 'POST', 'COMMENT', name='imagetype'), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
