"""新增第三方用户表

Revision ID: b3c934c4a64f
Revises: 834d2f86ae28
Create Date: 2026-01-22 14:59:52.572440

"""

# revision identifiers, used by Alembic.
revision = 'b3c934c4a64f'
down_revision = '834d2f86ae28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('blog', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('raw_user_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'uuid', name='uq_provider_uuid')
    )
    op.create_index('idx_provider_uuid', 'third_party_accounts', ['provider', 'uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_uuid', table_name='third_party_accounts')
    op.drop_table('third_party_accounts')
    # ### end Alembic commands ###
