"""增加文章的body_html字段

Revision ID: b9584696b505
Revises: None
Create Date: 2024-10-20 16:55:42.549797

"""

# revision identifiers, used by Alembic.
revision = 'b9584696b505'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
