"""用户表增加music字段

Revision ID: ed10582b0d7b
Revises: 3cbdaca38297
Create Date: 2025-11-06 23:23:55.540896

"""

# revision identifiers, used by Alembic.
revision = 'ed10582b0d7b'
down_revision = '3cbdaca38297'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import JSON

default_music = {
    "name": None,
    "artist": None,
    "url": None,
    "pic": None,
    "lrc": None,
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('music', sa.JSON(), nullable=True))
    # 补齐旧数据，让已注册的用户的music更新为默认值
    users = table('users', column('music', JSON))
    op.execute(
        users.update().where(users.c.music is None).values(music=default_music)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'music')
    # ### end Alembic commands ###
