"""更新评论 聊天表

Revision ID: f06b1721d987
Revises: 5cf3d7363540
Create Date: 2025-04-13 22:03:09.104440

"""

# revision identifiers, used by Alembic.
revision = 'f06b1721d987'
down_revision = '5cf3d7363540'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('root_comment_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('direct_parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['root_comment_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'comments', ['direct_parent_id'], ['id'])
    op.drop_column('comments', 'parent_comment_id')
    op.drop_column('comments', 'body_html')
    op.add_column('praise', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'praise', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'praise', type_='foreignkey')
    op.drop_column('praise', 'comment_id')
    op.add_column('comments', sa.Column('body_html', mysql.TEXT(), nullable=True))
    op.add_column('comments', sa.Column('parent_comment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_3', 'comments', 'comments', ['parent_comment_id'], ['id'])
    op.drop_column('comments', 'direct_parent_id')
    op.drop_column('comments', 'root_comment_id')
    op.drop_table('messages')
    # ### end Alembic commands ###
