"""Post表增加summary摘要字段

Revision ID: f67229d9f8fa
Revises: a315517f06bc
Create Date: 2025-12-18 21:58:27.041402

"""

# revision identifiers, used by Alembic.
revision = 'f67229d9f8fa'
down_revision = 'a315517f06bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(length=500), nullable=True))
    op.drop_column('posts', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('images', mysql.TEXT(), nullable=True))
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
